# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-10 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_config', '0006_rolconfig_roluser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulemodel',
            options={'ordering': ['-id']},
        ),
    ]
